### DISCUSSION TITLE
how to create VM with dhcp in

### DISCUSSION THREAD

**Discussion by spham** [ansible-community/molecule-vagrant#184] [Q&A]
Hi,

Is it possible to provisionning VM's with DHCP outside from private network ?

my molecule.yml file start like this
```
---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos7
    box: centos/7



  - name: rocky
    box: rockylinux/8
```

regards

**Comment by apatard** [comment]
I'm not sure to understand the question but I guess the idea would be to define a public network (for a definition of "public network" see https://www.vagrantup.com/docs/networking/public_network for instance). I've not tested but it should be something like :

```
    interfaces:
      - network_name: public_network
```

which should translate to the following Vagrantfile excerpt:

```
c.vm.network "public_network"
```

**Reply by spham** [reply]
I try this without success, because bidge is requested

```
platforms:
  - name: ubuntu2004
    box: ubuntu/focal64
    memory: 8096
    cpus: 1
    interfaces:
      - network_name: public_network
        type: dhcp
        auto_config: true
```

and have this

```
TASK [Create molecule instance(s)] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/vagrant", "up", "--no-provision"], "msg": "Failed to start the VM(s): See log file '/home/.cache/molecule/awx/default/vagrant.err'", "rc": 1, "stderr": "### 2022-09-16 09:38:41 ###\n### 2022-09-16 09:38:41 ###\nVagrant is attempting to interface with the UI in a way that requires\na TTY. Most actions in Vagrant that require a TTY have configuration\nswitches to disable this requirement. Please do that or run Vagrant\nwith TTY.\n", "stderr_lines": ["### 2022-09-16 09:38:41 ###", "### 2022-09-16 09:38:41 ###", "Vagrant is attempting to interface with the UI in a way that requires", "a TTY. Most actions in Vagrant that require a TTY have configuration", "switches to disable this requirement. Please do that or run Vagrant", "with TTY."]}
```
