### ISSUE TITLE
Incompatibility with ansible 4

### ISSUE THREAD

**Issue by Tcharl** [ansible-community/molecule-vagrant#109]
Hi,

Ansible 4.0.0, molecule-vagrant 0.6.3

And this molecule.yml file which works well with previous ansible (3.4.0)

```
---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    roles-path: ../community
    requirements-file: requirements-collections.yml
    collections-path: ../community-collections
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: master.osgiliath.test
    box: tcharl/fedora-33-cgroupv1
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kube_master
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE Controller', '--hostiocache', 'on']"
    instance_raw_config_args:
      - "cache.enable :dnf"
      - "cache.auto_detect = false"
  - name: node1.osgiliath.test
    box: tcharl/fedora-33-cgroupv1
    provider_options:
      cpus: 2
      memory: 2048
    groups:
      - kube_node
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE Controller', '--hostiocache', 'on']"
    instance_raw_config_args:
      - "cache.enable :dnf"
      - "cache.auto_detect = false"

provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#      gather_timeout: 20
#      timeout: 60
#    ssh_connection:
#      pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1

```

Leads to: 

```

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jinja2.exceptions.UndefinedError: 'network' is undefined
failed: [localhost] (item=node1.osgiliath.test) => {"ansible_loop_var": "item", "changed": false, "item": {"box": "tcharl/fedora-33-cgroupv1", "groups": ["kube_node"], "instance_raw_config_args": ["cache.enable :dnf", "cache.auto_detect = false"], "interfaces": [{"auto_config": true, "network_name": "private_network", "type": "dhcp"}], "name": "node1.osgiliath.test", "provider_options": {"cpus": 2, "memory": 2048}, "provider_raw_config_args": ["customize ['storagectl', :id, '--name', 'IDE Controller', '--hostiocache', 'on']"]}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\n  File \"/Users/charliemordant/.ansible/tmp/ansible-tmp-1621798180.079369-58781-116117760940889/AnsiballZ_vagrant.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/Users/charliemordant/.ansible/tmp/ansible-tmp-1621798180.079369-58781-116117760940889/AnsiballZ_vagrant.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/charliemordant/.ansible/tmp/ansible-tmp-1621798180.079369-58781-116117760940889/AnsiballZ_vagrant.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vagrant', init_globals=dict(_module_fqn='ansible.modules.vagrant', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/ansible_vagrant_payload_5mluspts/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 554, in <module>\n  File \"/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/ansible_vagrant_payload_5mluspts/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 539, in main\n  File \"/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/ansible_vagrant_payload_5mluspts/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 299, in __init__\n  File \"/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/ansible_vagrant_payload_5mluspts/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 434, in _write_configs\n  File \"/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/ansible_vagrant_payload_5mluspts/ansible_vagrant_payload.zip/ansible/modules/vagrant.py\", line 428, in _write_vagrantfile\n  File \"/usr/local/lib/python3.9/site-packages/molecule/util.py\", line 182, in render_template\n    return t.render(kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/jinja2/environment.py\", line 1304, in render\n    self.environment.handle_exception()\n  File \"/usr/local/lib/python3.9/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"<template>\", line 57, in top-level template code\n  File \"/usr/local/lib/python3.9/site-packages/jinja2/environment.py\", line 474, in getattr\n    return getattr(obj, attribute)\njinja2.exceptions.UndefinedError: 'network' is undefined\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

When `molecule create`

I triple checked every generated Vagrantfile and so on, but no clue...
