### ISSUE TITLE
memory setting ignored for Vbox

### ISSUE THREAD

**Issue by dhoer** [ansible-community/molecule-vagrant#115]
Trying to set memory with the following

```
driver:
  name: vagrant
  provider:
    name: VBox
platforms:
  - name: ubuntu14
    box: ubuntu/trusty64
    memory: 8192
```

But the memory remains at 512.

**Comment by apatard** [comment]
As may be seen in examples of Vagrantfiles with virtualbox here: https://www.vagrantup.com/docs/providers/virtualbox/configuration, the provider name is virtualbox (all lower case), so your ``molecule.yml`` should look like:

```
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu14
    box: ubuntu/trusty64
    memory: 8192
```
For now, using the wrong provider name will still get a VM created, even if the settings are kind-of ignored. I've been wondering for quite some time to add to the ``vagrant up`` command the ``--provider $providername`` argument which will possibly result in an error if the provider name is wrong. Unfortunately it may break some people setup....
