### ISSUE TITLE
The error was: jinja2.exceptions.UndefinedError: 'network' is undefined (with version 0.6.3)

### ISSUE THREAD

**Issue by vguillard** [ansible-community/molecule-vagrant#116]
My molecule/default/molecule.yml :
```
platforms:
  - name: default
    box: ${IMAGE_NAME:-ubuntu/xenial64}
    interfaces:
      - auto_config: false
        network_name: private_network
        type: dhcp
      - auto_config: false
        network_name: private_network
        type: dhcp
```

With molecule-vagrant 0.6.3, it doesn't work, i've got 'network is undefined' error message:
```
$ molecule --version
molecule 3.2.1 using python 3.6 
    ansible:2.9.16
    delegated:3.2.1 from molecule
    docker:0.2.4 from molecule_docker
    vagrant:0.6.3 from molecule_vagrant

$ molecule create
TASK [Create molecule instance(s)] ******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jinja2.exceptions.UndefinedError: 'network' is undefined
```

But it works with version 0.6.1
