### ISSUE TITLE
Network config broken in Vagrant 2.2.17

### ISSUE THREAD

**Issue by dbazile** [ansible-community/molecule-vagrant#119]
After updating Vagrant this morning, I'm seeing this error from molecule converge:

```
/opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/kernel_v2/config/vm.rb:319:in `network': wrong number of arguments (given 2, expected 1) (ArgumentError)
    from /home/dbazile/.cache/molecule/foo/default/Vagrantfile:201:in `block (3 levels) in <top (required)>'
    from /home/dbazile/.cache/molecule/foo/default/Vagrantfile:200:in `each'
    from /home/dbazile/.cache/molecule/foo/default/Vagrantfile:200:in `block (2 levels) in <top (required)>'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/v2/loader.rb:37:in `load'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/loader.rb:119:in `each'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/loader.rb:119:in `block in load'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/loader.rb:116:in `each'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/config/loader.rb:116:in `load'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/vagrantfile.rb:173:in `machine_config'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:959:in `block in find_configured_plugins'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:957:in `each'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:957:in `find_configured_plugins'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:984:in `process_configured_plugins'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:178:in `initialize'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:194:in `new'
    from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:194:in `<main>'
```

The section of the Vagrantfile that's being complained about (line 201):

```
   .
   .
   190	  ##
   191	  # Instances
   192	  ##
   193	
   194	  if vagrant_config_hash['instance']
   195	    instance = vagrant_config_hash['instance']
   196	    config.vm.define instance['name'] do |c|
   197	      c.vm.hostname = instance['name']
   198	
   199	      if instance['interfaces']
   200	        instance['interfaces'].each { |interface|
   201	          c.vm.network "#{interface['network_name']}",
   202	                       Hash[interface.select{|k| k != 'network_name'}.map{|k,v| [k.to_sym, v]}]
   203	        }
   204	      end
   205	
   206	      if instance['raw_config_args']
   207	        instance['raw_config_args'].each { |raw_config_arg|
   208	          eval("c.#{raw_config_arg}")
   209	        }
   210	      end
   211	    end
   .
   .
```

My molecule.yml:

```yml
---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: foo
    box: foo
    box_url: http://blahblah/foo
    memory: 2048
    cpus: 2
    interfaces:
      - network_name: private_network
        name: vboxnet1
        type: static
        ip: 192.168.1.111

provisioner:
  name: ansible
  options:
    D: true
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callback: true

verifier:
  name: ansible

lint:
  set -e
  yamllint .
  ansible-lint .
```

Apparently this is due to a change in how Ruby 3 handles call parameter expansion: https://github.com/hashicorp/vagrant/issues/12448

| package | version |
|---------------|--------------|
| molecule | 3.0.8 |
| molecule-vagrant | 0.3 |
| vagrant | 2.2.17 |
