### ISSUE TITLE
Add a disk

### ISSUE THREAD

**Issue by markfaine** [ansible-community/molecule-vagrant#127]
I reviewed the docs but didn't see anyway to configure an additional disk.  I need to test an LVM role and I need a second disk device.  Is this possible?

**Comment by apatard** [comment]
It has to be done through provider specific options. For instance, with vagrant libvirt (I don't have virtualbox example at hand):
```
...
driver:
  name: vagrant
  provider:
    name: libvirt
...
platforms:
- name: vm
  box: debian/buster64
  provider_raw_config_args:
  - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
...
```
