### ISSUE TITLE
memory setting seems ignored when using libvirt

### ISSUE THREAD

**Issue by aogier** [ansible-community/molecule-vagrant#152]
Hi, I'm using this config

```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: debian/buster64
    memory: 3072
    cpu: 2
provisioner:
  name: ansible
verifier:
  name: ansible
```

but no luck on having `memory`, `cpu` honored. Is there something I've missed? I see similar(ish) issues but nothing that could seems to help me in this case...

Thank you, ciao!

**Comment by apatard** [comment]
Did you try something like that ? :
```
driver:
  name: vagrant
  provider:
    name: libvirt
```
