### ISSUE TITLE
Failed to create the raw output file

### ISSUE THREAD

**Issue by faruqisan** [ansible-community/molecule-vagrant#17]
Hi, I tried to run my molecule test on this environment:

OS: Ubuntu 18.04
Molecule: 3.0.2
Ansible: 2.9.6
Python: 3.6

I use venv.

When I try to run `molecule test` it fails on create step, here is the error log:

```bash
failed: [localhost] (item=instance) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/vagrant", "up", "--provision"], "item": {"box": "gopaytech/postgresql", "box_version": "0.0.3", "instance_raw_config_args": ["vm.network 'private_network', ip: '192.168.44.10'"], "interfaces": [{"auto_config": true, "network_name": "private_network", "type": "dhcp"}], "name": "instance", "provision": true}, "msg": "ERROR: See log file '/home/my-user/.cache/molecule/postgresql-basic-config/default/vagrant-instance.err'", "rc": 1, "stderr": "### 2020-03-18 19:54:35 ###\n### 2020-03-18 19:54:35 ###\nThere was an error while executing `VBoxManage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"startvm\", \"6d587526-d3af-4e54-8984-7033999a43ce\", \"--type\", \"headless\"]\n\nStderr: VBoxManage: error: RawFile#0 failed to create the raw output file /Users/my-user/workspace/packers/postgresql-image-packer/ubuntu-bionic-18.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole\n", "stderr_lines": ["### 2020-03-18 19:54:35 ###", "### 2020-03-18 19:54:35 ###", "There was an error while executing `VBoxManage`, a CLI used by Vagrant", "for controlling VirtualBox. The command and stderr is shown below.", "", "Command: [\"startvm\", \"6d587526-d3af-4e54-8984-7033999a43ce\", \"--type\", \"headless\"]", "", "Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /Users/my-user/workspace/packers/postgresql-image-packer/ubuntu-bionic-18.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)", "VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole"]}
```

I think it's failed because molecule tried to write file to `/User/my-user/. . .` which doesn't exist on Ubuntu.

And, my working dir is:

`/home/my-user/workspace/ansible-roles/postgresql-basic-config`

Why molecule tried to write to another folder? is it cached or something?

How to fix this?

**Comment by apatard** [comment]
Please, can you provide a way to reproduce the bug, at least your ``molecule.yml`` file in order to try to reproduce it ?

**Comment by faruqisan** [comment]
Sorry, I forgot to put how to reproduce, here are my molecule.yaml:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.44.10'"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    box: "gopaytech/postgresql"
    box_version: 0.0.3
    provision: True
provisioner:
  name: ansible
verifier:
  name: ansible
```

Additional information:

The box I use is build using Packer, on my Macbook. and I realize that the error caused by it tried to write the log file to my Mac pc path.

**Comment by apatard** [comment]
I've reproduced similar issue with the box ``gopaytech/postgresql`` box but not with an other image like ``debian/buster64``. In fact, I get it with vagrant directly, with a vagrantfile and not with molecule.
If you look at the box configuration file from the vagrant box, you'll find that the VM has a serial port enabled, configured to write the output to a file, so:
- either the box should not enable the serial port by default
- or the user of the box has to take care of configuring the serial port inside ``molecule.yml``

I'm not sure what's the current practice regarding Virtualbox Vagrant boxes and serial port. It's possible that it's not recommended ?

As regards disabling the vbox uart by default from molecule, I'm not sure if it's really possible, so I would tend to believe that the solution is the one you gave, aka using ``provider_raw_config_args``.
@ssbarnea any opinion about this ?

**Comment by faruqisan** [comment]
Thanks, @apatard , currently I'm investigating this issue from [Packer](https://packer.io/) side. this is may caused by some misconfigured builder.

**Comment by ssbarnea** [comment]
I am not using the vagrant driver anywhere in production so I am unable to give good advice.

Still, I am reluctant to change defaults unless we have a very good selling point, like that it fixes 9/10 images or that it very unlikely to break any of the others.

If that is not possible, updating the documentation to mention it could be another decent fix.

**Comment by karcaw** [comment]
I've seen what I believe is the same issue with other vagrant creates.  one with the ubuntu/bionic64 which gives the error:
```
Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /usr/local/lib/python3.6/dist-packages/molecule_vagrant/playbooks/ubuntu-bionic-18.04-cloudimg-console.log (VERR_ACCESS_DENIED)
```

and in another test where i added customizations to a centos7 image:
```
VBoxManage: error: Could not create the medium storage unit '/usr/local/lib/python3.6/dist-packages/molecule_vagrant/playbooks/machine1_disk0.vdi'
```

molecule.yaml
```yaml
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  pre-commit run -a
platforms:
  - name: ceph-test-host
    box: msc/centos-7.6
    box_url: http://<redacted>/centos-7.6.json
    provider_raw_config_args:
      - "customize ['createhd',  '--filename', 'machine1_disk0', '--size', '8196']"
      - "customize ['createhd',  '--filename', 'machine1_disk1', '--size', '8196']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '1', '--type', 'hdd', '--medium', 'machine1_disk0.vdi']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '2', '--type', 'hdd', '--medium', 'machine1_disk1.vdi']"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
```

in both cases, it seems that the molecule-vagrant plugin is trying to create files not in the molecule_ephemeral_directory or some other appropriate place.

**Comment by apatard** [comment]
@karcaw I believe your issue is a different one. I guess that your issue is that vboxmanage, without any full file path given, will create the files/vdi in the current directory. The bug here is that the full path to the serial log file is hardcoded to a local path in the box file. Can you please open a different bug ? [fwiw, I've even a clue of how to solve that]

**Comment by karcaw** [comment]
opened #20

**Comment by apatard** [comment]
@faruqisan any news / progress ?

**Comment by faruqisan** [comment]
Hi, It's solved by adding this line:

```yaml
 provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
```

complete file:

```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: pg-master
    instance_raw_config_args:
        - "vm.network 'private_network', ip: '192.168.44.10'"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    box: "gopaytech/postgresql"
    box_version: 12.0.0
    provision: True
provisioner:
  name: ansible
verifier:
  name: ansible
```
