### ISSUE TITLE
vagrant create tries to make files in the python system directories

### ISSUE THREAD

**Issue by karcaw** [ansible-community/molecule-vagrant#20]
I have been seeing issues when creating systems on an ubuntu 18.04 machine. 

One with the ubuntu/bionic64 which gives the error:
```
Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /usr/local/lib/python3.6/dist-packages/molecule_vagrant/playbooks/ubuntu-bionic-18.04-cloudimg-console.log (VERR_ACCESS_DENIED)
```

and in another test where i added customizations to a centos7 image:
```
VBoxManage: error: Could not create the medium storage unit '/usr/local/lib/python3.6/dist-packages/molecule_vagrant/playbooks/machine1_disk0.vdi'
```

molecule.yaml
```yaml
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  pre-commit run -a
platforms:
  - name: ceph-test-host
    box: msc/centos-7.6
    box_url: http://<redacted>/centos-7.6.json
    provider_raw_config_args:
      - "customize ['createhd',  '--filename', 'machine1_disk0', '--size', '8196']"
      - "customize ['createhd',  '--filename', 'machine1_disk1', '--size', '8196']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '1', '--type', 'hdd', '--medium', 'machine1_disk0.vdi']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '2', '--type', 'hdd', '--medium', 'machine1_disk1.vdi']"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
```

in both cases, it seems that the molecule-vagrant plugin is trying to create files not in the molecule_ephemeral_directory or some other appropriate place.

I am using virtualbox 6.1 and vagrant 2.2.7
