### ISSUE TITLE
How to set/override libvirt provider options?

### ISSUE THREAD

**Issue by stdevel** [ansible-community/molecule-vagrant#41]
Hi folks,
for some Vagrant boxes (*generic/opensuse15* and *roboxes/opensuse15*) I need to override the `disk_bus` provider option in order to boot the VM. In a pure Vagrantfile, this is kinda easy:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/opensuse15"
  config.vm.box_version = "3.0.18"
  config.vm.provider :libvirt do |libvirt|
    libvirt.disk_bus = "sata"
  end
end
```

But I can't figure out how to set this in `molecule.yml`. From the molecule-vagrant documentation I understand that there are both `provider_options` and `provider_raw_config_args`, but I'm not very successful.

I tried several configuration arguments, currently my `molecule.yml` looks like this:

```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: opensuse-leap15
    box: generic/opensuse15
    cpus: 2
    memory: 4096
    provider_options:
      disk_bus: "sata"
      libvirt.disk_bus: "sata"
      domain.disk_bus: "sata"
    provider_raw_config_args:
      - 'disk_bus = "sata"'
      - 'libvirt.disk_bus = "sata"'
      - 'domain.disk_bus = "sata"'
providers:
  - name: libvirt
    type: libvirt
    options:
      disk_bus: "sata"
      libvirt.disk_bus: "sata"
      domain.disk_bus: "sata"
provisioner:
  name: ansible
verifier:
  name: testinfra
```

Am I missing something?

**Comment by apatard** [comment]
Which version of molecule-vagrant are you using ? it should be working with 0.3. Any older version are broken.


The current test suite is setting `nic_model_type` and not `disk_bus` (see https://github.com/ansible-community/molecule-vagrant/blob/master/molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml). I believe in should work in a same way.

**Comment by stdevel** [comment]
Hey @apatard,
thanks for your fast reply!

I'm using version 0.3:

```shell
$ pip3 freeze |grep molecule-vagrant
molecule-vagrant==0.3
```

Thanks for the example, so setting `provider_options` per instance should work, also the format is quite the same. It just seems to ignore the `disk_bus` directive. Doing it manually works like a charm.

Any other ideas?

**Comment by apatard** [comment]
Did you check the quotes ? 0.3 needs something like `disk_bus: '"sata"'`.

**Comment by apatard** [comment]
did you manage to get it working ?
fwiw, here is a modified version of the molecule.yml of the test I was talking of:
```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  /bin/true
platforms:
- name: instance
  provider_options:
    disk_bus: '"sata"'
  box: debian/buster64
provisioner:
  name: ansible
verifier:
  name: ansible
```
and it seems to be working:
```xml
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/default_instance.img'/>
      <backingStore type='file' index='1'>
        <format type='qcow2'/>
        <source file='/var/lib/libvirt/images/debian-VAGRANTSLASH-buster64_vagrant_box_image_10.4.0.img'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='sata'/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```

**Comment by apatard** [comment]
Hi.
@stdevel : Any news on this ?

**Comment by apatard** [comment]
Hi,
I've provided a solution but no news about it fixing or not the issue for months. I'm going to close this issue. If the issue is still valid, please open a new bug. Thanks.

**Comment by stdevel** [comment]
Hi @apatard,
Sorry for ghosting you so long - totally missed to have a look at your suggestions. Thanks a lot for them!

I upgraded `molecule` and the `molecule-vagrant` module to the very latest versions:

```
molecule==3.2.0
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6
```

Also, I tried setting the `disk_bus` setting:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    provider_options:
      disk_bus: '"sata"'
    box: generic/opensuse15
provisioner:
  name: ansible
verifier:
  name: ansible
```

Anyhow, I'm getting the following error:

```
Path: <provider config: libvirt>
Line number: 179
Message: NoMethodError: undefined method `include?' for nil:NilClass
### 2020-12-05 09:01:05 ###
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: libvirt>
Line number: 179
Message: NoMethodError: undefined method `include?' for nil:NilClass
```

I double-checked the `disk_bus` value and also tried both `'"sata"'` and `"'sata'"` - both seem not to work.
Am I missing something?
