### ISSUE TITLE
How disable audio and video in virtualbox vm molecule test?

### ISSUE THREAD

**Issue by Daniel-Sanchez-Fabregas** [ansible-community/molecule-vagrant#42]
To disable audio and video in virtualbox vm this `Vagrantfile` works for me:
``` ruby
# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'none']
    vb.customize ['modifyvm', :id, '--audio', 'none']
  end
end
```

What is the correct `molecule.yml` to reproduce the above `Vagrantfile` in molecule?

My failed attempts (one with `raw_config_args`, other with `override_args`) that have `VBoxVGA` and `Pulseaudio` instead of None:

``` yaml
---
# molecule.yml
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: centos/7
    raw_config_args:
    # override_args:
      # Disable video
      - 'vb.gui = false'
      - 'vb.customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      # Disable audio
      - 'vb.customize ["modifyvm", :id, "--audio", "none"]'
provisioner:
  name: ansible
verifier:
  name: ansible
```

Tested in this environment:

``` sh
$ pip freeze | grep molecule
molecule==3.0.8
molecule-vagrant==0.3

$ molecule --version
molecule 3.0.8
   ansible==2.9.6 python==3.8

$ vagrant --version
Vagrant 2.2.9

$ inxi -S
System:    Host: workmachine Kernel: 5.7.15-200.fc32.x86_64 x86_64 bits: 64 Desktop: MATE 1.24.0 
           Distro: Fedora release 32 (Thirty Two) 
```

**Comment by karcaw** [comment]
set the gui in provider options and customize in provider_raw_config_args:
```
platforms:
  - name: ubuntu1804
    provider_options:
      gui: true
    provider_raw_config_args:
      - "customize ['createhd',  '--filename', 'machine1_disk0', '--size', '8196']"
      - "customize ['createhd',  '--filename', 'machine1_disk1', '--size', '8196']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '1', '--type', 'hdd', '--medium', 'machine1_disk0.vdi']"
      - "customize ['storageattach', :id, '--storagectl', 'SATA Controller','--port', '2', '--type', 'hdd', '--medium', 'machine1_disk1.vdi']"
 
```

**Comment by Daniel-Sanchez-Fabregas** [comment]
Thanks @karcaw !

This solves a weird `x2go` - `pulseaudio` - `virtualbox` bug that would freeze my session every time I execute `molecule creation`

``` yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: centos/7
    provider_options:
      gui: false
    provider_raw_config_args:
      # Disable video
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
provisioner:
  name: ansible
verifier:
  name: ansible

```
