### ISSUE TITLE
vm is always provisioned with alpine box

### ISSUE THREAD

**Issue by odra** [ansible-community/molecule-vagrant#96]
Hello,

I am trying to use this driver to test my role in a centos box but it is always using an alpine box, here is `molecule.yml` file:

```yml
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: myrole
    box: centos/8
    memory: 512
    cpus: 1
    instance_raw_config_args:
      - vagrant.plugins = ["vagrant-libvirt"]
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: false
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080
    provision: no
provisioner:
  name: ansible
verifier:
  name: ansible
``` 

Output of `molecule --version`:

```
molecule 3.2.0a0
    ansible:2.10.3 python:3.6
    delegated:3.2.0a0 from molecule
    docker:0.3.3 from molecule_docker
    vagrant:0.6.1 from molecule_vagrant
```

Am I missing something or is the box property being used in the wrong place?

Thanks!
