### ISSUE TITLE
ERROR! couldn't resolve module/action 'molecule_vagrant'.

### ISSUE THREAD

**Issue by dzintars** [ansible-community/molecule-vagrant#99]
Hi, will report that i came across this error when trying to:
```yaml
# molecule/default/create.yml
---
- name: Create
  hosts: localhost
  connection: local
  tasks:
    - name: Create instance
      molecule_vagrant:
        instance_name: "{{ item }}"
        platform_box: ubuntu/trusty64
        .......
```

```sh
ERROR! couldn't resolve module/action 'molecule_vagrant'. This often indicates a misspelling, missing collection, or incorrect module path.
```
```bash
» molecule --version
molecule 3.2.3 using python 3.9
    ansible:2.10.5
    delegated:3.2.3 from molecule
    podman:0.3.0 from molecule_podman
    vagrant:0.6.1 from molecule_vagrant
```
```bash
» ansible --version
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dzintars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```
Installed via `pip install --user molecule-vagrant`

Context:
Using Molecule to test several playbooks across different Libvirt hosts + utilizing Collections.
Converge stage works well if i skip the create.

Similar issues:
https://github.com/ansible-community/molecule-vagrant/issues/8
